# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.2.0
maven_group = net.rosemarythyme.simplymore
archives_name = simplymore
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.3
yarn_mappings_patch_neoforge_version = 1.21+build.4

# Dependencies
architectury_api_version = 13.0.8
fabric_loader_version = 0.16.14
fabric_api_version = 0.115.1+1.21.1
neoforge_version = 21.1.133
fzzy_config_version = 0.6.9+1.21
mythicmetals_version=0.24.0+1.21

spruceui_version=5.0.0+1.20
mod_menu_version=4.0.5
cloth_config_version=11.1.106

simplyswords_fabric_version=6751811
simplyswords_neoforge_version=6751823